  global_frame: $(arg robot_id)/map
  robot_base_frame: $(arg robot_id)/base_footprint
  always_send_full_costmap: false
  resolution: 0.05

  footprint_padding: 0.01
  cost_scaling_factor: 30.0
  lethal_cost_threshold: 100
  allow_unknown: false
  track_unknown_space:  true
  unknown_cost_value: 254

  static_layer:
    enabled: true

  lidar_obstacle_layer:
    inflate_unknown: true
    enabled: true
    footprint_clearing_enabled: true
    max_obstacle_height: 0.5
    track_unknown_space:  true
    clear_on_max_reading: true
    observation_persistence: 0.07
    combination_method: 1
    observation_sources: lidar_scan
    lidar_scan:
      sensor_frame: $(arg robot_id)/scan
      expected_update_rate: 14.0
      max_obstacle_height: 0.5
      min_obstacle_height: 0.0
      data_type: LaserScan
      topic: /$(arg robot_id)/scan
      marking: true
      clearing: true

    enabled: true
    track_unknown_space: true        #default space is unknown
    max_obstacle_height: 2.0         #meters
    update_footprint_enabled: true
    combination_method: 1            #1=max, 0=override
    obstacle_range: 11.5             #meters


  inflation_layer:
    enabled: true
    cost_scaling_factor: 10.0
    inflate_unknown: true
    inflation_radius: 0.6
