global_costmap:
  obstacle_range: 11.5
  raytrace_range: 11.0
  update_frequency: 2.0
  rolling_window: false
  publish_frequency: 2.0
  transform_tolerance: 0.5

  robot_radius: 0.18
  inflation_radius: 10.0

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: lidar_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_layer:
    track_unknown_space:  true
    allow_unknown: false
    enabled: true
    cost_scaling_factor: 100.0
    inflate_unknown: true
    inflation_radius: 10.0

