shutdown_costmaps: false
controller_frequency: 20.0
planner_patience: 5.0
controller_patience: 15.0
planner_frequency: 1.0
robot_radius: 0.18

oscillation_timeout: 10.0
oscillation_distance: 0.2
conservative_reset_dist: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true
recovery_behaviors:
  - {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
  - {name: rotate_recovery, type: rotate_recovery/RotateRecoveryCute}
  - {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}

conservative_reset:
  reset_distance: 3.0

aggressive_reset:
  reset_distance: 0.0
