mkmr_controller:
  type: "mecanum_drive_controller/MecanumDriveController"
  publish_rate: 50.0

  front_left_wheel_joint: $(arg robot_id)/front_left_wheel_joint    # wheel 0
  back_left_wheel_joint: $(arg robot_id)/rear_left_wheel_joint      # wheel 1
  back_right_wheel_joint: $(arg robot_id)/rear_right_wheel_joint    # wheel 2
  front_right_wheel_joint: $(arg robot_id)/front_right_wheel_joint  # wheel 3
 

  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

  cmd_vel_timeout: 0.5

  base_frame_id: $(arg robot_id)/base_footprint 
  odom_frame_id: $(arg robot_id)/odom

  wheel_radius : 0.04
  enable_odom_tf: true

  open_loop: false

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.0   # m/s^2
    y:
      has_velocity_limits    : true
      max_velocity           : 0.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.0   # rad/s^2


