
#goal definition
bool RunTaskBase
bool Start
bool Continue
bool Pause
bool Cancel
string TargetName
---
#result definition
int32[] sequence
---
#feedback
string TargetName
string LastDoneTargetName
string STATE
